# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        pose: robot0/pose
        pose2d: robot0/ground_pose
        frame_id: robot0/base_link
    '1':
        pose: robot1/pose
        pose2d: robot1/ground_pose
        frame_id: robot1/base_link
    '2':
        pose: robot2/pose
        pose2d: robot2/ground_pose
        frame_id: robot2/base_link
